# Generated by Django 5.0.1 on 2024-01-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
