# Generated by Django 5.0.1 on 2024-01-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_rename_phone_doctor_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='fk_idnumber',
            new_name='idnumber',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='fk_staffid',
            new_name='staffid',
        ),
    ]
