# Generated by Django 5.0.1 on 2024-01-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_rename_fk_idnumber_appointments_idnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='idnumber',
            new_name='IDnumber',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='staffid',
            new_name='Staffid',
        ),
    ]
