# Generated by Django 5.0.1 on 2024-01-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_rename_idnumber_appointments_idnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='Staffid',
            new_name='Doctor_Staffid',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='IDnumber',
            new_name='Patient_IDnumber',
        ),
    ]
