# Generated by Django 5.0.1 on 2024-01-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_rename_staffid_appointments_doctor_staffid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visits',
            old_name='fk_staffid',
            new_name='Doctor_staffid',
        ),
        migrations.RenameField(
            model_name='visits',
            old_name='fk_idnumber',
            new_name='Patient_idnumber',
        ),
    ]
